source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/padding/YQPods.git'

use_frameworks!
platform :ios, '10.0'

target 'YQNetworking_Example' do
  pod 'YQNetworking', :path => '../'

  #pod 'Moya/RxSwift'
  #pod 'SnapKit'
  #pod 'RxDataSources'
  #pod 'YQLogger', :path => '../../YQLogger'
  target 'YQNetworking_Tests' do
    inherit! :search_paths

    
  end
end
